# Copyright (c) 2018 by Paderborn University
# (manuel@peuster.de)
# ALL RIGHTS RESERVED.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Neither the name of the OSM, Paderborn University
# nor the names of its contributors may be used to endorse or promote
# products derived from this software without specific prior written
# permission.
---
descriptor_extension: yml
version: '0.5'
files:
  - path: tango_emulator_example.yml
    type: application/vnd.5gtango.nsd
    tags:
      - eu.5gtango
  - path: tango_default-vnf0.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
  - path: tango_default-vnf1.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
package:
  name: emulator-example-service
  version: '0.1'
  maintainer: Manuel Peuster (Paderborn University)
  vendor: eu.5gtango
  description: >-
    This is a small example service to showcase how vim-emu can deploy simple
    5GTANGO network service packages.
